# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.

FROM jupyter/pyspark-notebook:0017b56d93c9

RUN pip install jupyter_kernel_gateway==0.5.0
# install ipywidgets 5.0
RUN pip install 'ipywidgets==5.0'

# install Declarative Widgets python package
# don't bother activating the extension, not needed outside notebook
ARG DECLARATIVE_WIDGETS='jupyter_declarativewidgets==0.5.1'
COPY ./declarativewidgets/dist/ /src/
RUN pip install $DECLARATIVE_WIDGETS

# run kernel gateway, not notebook server
CMD ["jupyter", "kernelgateway", "--KernelGatewayApp.ip=0.0.0.0"]
