# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.

---
version: "2"

services:
  notebook:
    build:
      context: .
      dockerfile: Dockerfile.notebook
      args:
          # pip versioning:
          DASHBOARDS_VER: '0.5.2'
          DECLWIDGETS_VER: '0.5.1'
          CMS_VER: '0.5.0'
          BUNDLER_VER: '0.7.0'
    ports:
      - "8888:8888"
    depends_on:
      - dashboards
    links:
      - dashboards
    volumes:
      - work:/home/jovyan/work
    environment:
        DASHBOARD_REDIRECT_URL: http://{hostname}:3000/
        DASHBOARD_SERVER_URL: http://dashboards:3000/
        DASHBOARD_SERVER_AUTH_TOKEN: notebook_to_dashboard_secret
        PASSWORD: demo

  dashboards:
    build:
      context: .
      dockerfile: Dockerfile.dashboards
      args:
          # npm versioning:
          DASHBOARDS_SERVER_VER: '>=0.5.0 <0.6.0'
    ports:
      - "3000:3000"
    depends_on:
      - kernel_gateway
    links:
      - kernel_gateway
    environment:
      PORT: 3000
      KERNEL_GATEWAY_URL: http://kernel_gateway:8888
      AUTH_TOKEN: notebook_to_dashboard_secret
      USERNAME: demo
      PASSWORD: demo

  kernel_gateway:
    build:
      context: .
      dockerfile: Dockerfile.kernel
      args:
          # pip versioning:
          IPYWIDGETS_VER: '5.0'
          DECLWIDGETS_VER: '0.5.1'
    environment:
      KG_ALLOW_ORIGIN: '*'

volumes:
  work:
